// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCertificateByCode = `-- name: GetCertificateByCode :one
SELECT id, code, user_id, course_id, student_name, course_title, issued_at, revoked_at FROM certificate.certificates WHERE code = $1
`

func (q *Queries) GetCertificateByCode(ctx context.Context, code string) (CertificateCertificate, error) {
	row := q.db.QueryRow(ctx, getCertificateByCode, code)
	var i CertificateCertificate
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UserID,
		&i.CourseID,
		&i.StudentName,
		&i.CourseTitle,
		&i.IssuedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getPolicy = `-- name: GetPolicy :one
SELECT course_id, mode, exam_id, updated_at FROM certificate.policies WHERE course_id = $1
`

func (q *Queries) GetPolicy(ctx context.Context, courseID int64) (CertificatePolicy, error) {
	row := q.db.QueryRow(ctx, getPolicy, courseID)
	var i CertificatePolicy
	err := row.Scan(
		&i.CourseID,
		&i.Mode,
		&i.ExamID,
		&i.UpdatedAt,
	)
	return i, err
}

const getValidCertificate = `-- name: GetValidCertificate :one
SELECT id, code, user_id, course_id, student_name, course_title, issued_at, revoked_at FROM certificate.certificates
WHERE course_id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type GetValidCertificateParams struct {
	CourseID int64
	UserID   int64
}

func (q *Queries) GetValidCertificate(ctx context.Context, arg GetValidCertificateParams) (CertificateCertificate, error) {
	row := q.db.QueryRow(ctx, getValidCertificate, arg.CourseID, arg.UserID)
	var i CertificateCertificate
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UserID,
		&i.CourseID,
		&i.StudentName,
		&i.CourseTitle,
		&i.IssuedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertCertificate = `-- name: InsertCertificate :one
INSERT INTO certificate.certificates (id, code, user_id, course_id, student_name, course_title, issued_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT DO NOTHING
RETURNING id
`

type InsertCertificateParams struct {
	ID          int64
	Code        string
	UserID      int64
	CourseID    int64
	StudentName string
	CourseTitle string
	IssuedAt    time.Time
}

// Returns no row when the user already holds a valid certificate for the course.
func (q *Queries) InsertCertificate(ctx context.Context, arg InsertCertificateParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertCertificate,
		arg.ID,
		arg.Code,
		arg.UserID,
		arg.CourseID,
		arg.StudentName,
		arg.CourseTitle,
		arg.IssuedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listCertificatesByUser = `-- name: ListCertificatesByUser :many
SELECT id, code, user_id, course_id, student_name, course_title, issued_at, revoked_at FROM certificate.certificates
WHERE user_id = $1
ORDER BY issued_at DESC, id DESC
`

func (q *Queries) ListCertificatesByUser(ctx context.Context, userID int64) ([]CertificateCertificate, error) {
	rows, err := q.db.Query(ctx, listCertificatesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CertificateCertificate
	for rows.Next() {
		var i CertificateCertificate
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.UserID,
			&i.CourseID,
			&i.StudentName,
			&i.CourseTitle,
			&i.IssuedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeValidCertificate = `-- name: RevokeValidCertificate :exec
UPDATE certificate.certificates SET revoked_at = $3
WHERE course_id = $1 AND user_id = $2 AND revoked_at IS NULL AND issued_at <= $4
`

type RevokeValidCertificateParams struct {
	CourseID  int64
	UserID    int64
	RevokedAt *time.Time
	IssuedBy  time.Time
}

func (q *Queries) RevokeValidCertificate(ctx context.Context, arg RevokeValidCertificateParams) error {
	_, err := q.db.Exec(ctx, revokeValidCertificate,
		arg.CourseID,
		arg.UserID,
		arg.RevokedAt,
		arg.IssuedBy,
	)
	return err
}

const upsertPolicy = `-- name: UpsertPolicy :exec
INSERT INTO certificate.policies (course_id, mode, exam_id, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (course_id) DO UPDATE SET
  mode = EXCLUDED.mode,
  exam_id = EXCLUDED.exam_id,
  updated_at = EXCLUDED.updated_at
`

type UpsertPolicyParams struct {
	CourseID  int64
	Mode      string
	ExamID    pgtype.Int8
	UpdatedAt time.Time
}

func (q *Queries) UpsertPolicy(ctx context.Context, arg UpsertPolicyParams) error {
	_, err := q.db.Exec(ctx, upsertPolicy,
		arg.CourseID,
		arg.Mode,
		arg.ExamID,
		arg.UpdatedAt,
	)
	return err
}
