// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"
)

const applyLectureBlockOrder = `-- name: ApplyLectureBlockOrder :exec
UPDATE courseauthoring.lecture_blocks b
SET position = o.position - 1, updated_at = $1::timestamptz
FROM unnest($3::text[]) WITH ORDINALITY AS o(client_block_id, position)
WHERE b.lecture_id = $2::bigint
  AND b.client_block_id = o.client_block_id
  AND b.position IS DISTINCT FROM (o.position - 1)
`

type ApplyLectureBlockOrderParams struct {
	Now            time.Time
	LectureID      int64
	ClientBlockIds []string
}

// The position unique constraint is deferred, so permuting positions in one
// statement is allowed. Rows already in place are skipped.
func (q *Queries) ApplyLectureBlockOrder(ctx context.Context, arg ApplyLectureBlockOrderParams) error {
	_, err := q.db.Exec(ctx, applyLectureBlockOrder, arg.Now, arg.LectureID, arg.ClientBlockIds)
	return err
}

const bumpLectureContentRevision = `-- name: BumpLectureContentRevision :execrows
UPDATE courseauthoring.lectures
SET content_revision = content_revision + 1, updated_at = $3
WHERE id = $1 AND content_revision = $2
`

type BumpLectureContentRevisionParams struct {
	ID              int64
	ContentRevision int64
	UpdatedAt       time.Time
}

func (q *Queries) BumpLectureContentRevision(ctx context.Context, arg BumpLectureContentRevisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, bumpLectureContentRevision, arg.ID, arg.ContentRevision, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLectureBlocks = `-- name: DeleteLectureBlocks :exec
DELETE FROM courseauthoring.lecture_blocks WHERE lecture_id = $1
`

func (q *Queries) DeleteLectureBlocks(ctx context.Context, lectureID int64) error {
	_, err := q.db.Exec(ctx, deleteLectureBlocks, lectureID)
	return err
}

const deleteLectureBlocksByClientIDs = `-- name: DeleteLectureBlocksByClientIDs :exec
DELETE FROM courseauthoring.lecture_blocks
WHERE lecture_id = $1 AND client_block_id = ANY($2::text[])
`

type DeleteLectureBlocksByClientIDsParams struct {
	LectureID      int64
	ClientBlockIds []string
}

func (q *Queries) DeleteLectureBlocksByClientIDs(ctx context.Context, arg DeleteLectureBlocksByClientIDsParams) error {
	_, err := q.db.Exec(ctx, deleteLectureBlocksByClientIDs, arg.LectureID, arg.ClientBlockIds)
	return err
}

const deleteLecturesNotIn = `-- name: DeleteLecturesNotIn :exec
DELETE FROM courseauthoring.lectures
WHERE course_id = $1 AND NOT (id = ANY($2::bigint[]))
`

type DeleteLecturesNotInParams struct {
	CourseID int64
	Keep     []int64
}

func (q *Queries) DeleteLecturesNotIn(ctx context.Context, arg DeleteLecturesNotInParams) error {
	_, err := q.db.Exec(ctx, deleteLecturesNotIn, arg.CourseID, arg.Keep)
	return err
}

const deleteSectionsNotIn = `-- name: DeleteSectionsNotIn :exec
DELETE FROM courseauthoring.sections
WHERE course_id = $1 AND NOT (id = ANY($2::bigint[]))
`

type DeleteSectionsNotInParams struct {
	CourseID int64
	Keep     []int64
}

func (q *Queries) DeleteSectionsNotIn(ctx context.Context, arg DeleteSectionsNotInParams) error {
	_, err := q.db.Exec(ctx, deleteSectionsNotIn, arg.CourseID, arg.Keep)
	return err
}

const forceBumpLectureContentRevision = `-- name: ForceBumpLectureContentRevision :one
UPDATE courseauthoring.lectures
SET content_revision = content_revision + 1, updated_at = $2
WHERE id = $1
RETURNING content_revision
`

type ForceBumpLectureContentRevisionParams struct {
	ID        int64
	UpdatedAt time.Time
}

func (q *Queries) ForceBumpLectureContentRevision(ctx context.Context, arg ForceBumpLectureContentRevisionParams) (int64, error) {
	row := q.db.QueryRow(ctx, forceBumpLectureContentRevision, arg.ID, arg.UpdatedAt)
	var content_revision int64
	err := row.Scan(&content_revision)
	return content_revision, err
}

const getLectureHeader = `-- name: GetLectureHeader :one
SELECT id, course_id, title, free_preview, content_revision
FROM courseauthoring.lectures WHERE course_id = $1 AND id = $2
`

type GetLectureHeaderParams struct {
	CourseID int64
	ID       int64
}

type GetLectureHeaderRow struct {
	ID              int64
	CourseID        int64
	Title           string
	FreePreview     bool
	ContentRevision int64
}

func (q *Queries) GetLectureHeader(ctx context.Context, arg GetLectureHeaderParams) (GetLectureHeaderRow, error) {
	row := q.db.QueryRow(ctx, getLectureHeader, arg.CourseID, arg.ID)
	var i GetLectureHeaderRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.FreePreview,
		&i.ContentRevision,
	)
	return i, err
}

const getLectureHeaderForUpdate = `-- name: GetLectureHeaderForUpdate :one
SELECT id, course_id, title, free_preview, content_revision
FROM courseauthoring.lectures WHERE course_id = $1 AND id = $2
FOR UPDATE
`

type GetLectureHeaderForUpdateParams struct {
	CourseID int64
	ID       int64
}

type GetLectureHeaderForUpdateRow struct {
	ID              int64
	CourseID        int64
	Title           string
	FreePreview     bool
	ContentRevision int64
}

func (q *Queries) GetLectureHeaderForUpdate(ctx context.Context, arg GetLectureHeaderForUpdateParams) (GetLectureHeaderForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getLectureHeaderForUpdate, arg.CourseID, arg.ID)
	var i GetLectureHeaderForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.FreePreview,
		&i.ContentRevision,
	)
	return i, err
}

const insertCourse = `-- name: InsertCourse :exec
INSERT INTO courseauthoring.courses
  (id, owner_id, title, description, level, thumbnail_url, status, price_amount_minor, price_currency, version, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 1, $10, $11)
`

type InsertCourseParams struct {
	ID               int64
	OwnerID          int64
	Title            string
	Description      string
	Level            string
	ThumbnailUrl     string
	Status           string
	PriceAmountMinor int64
	PriceCurrency    string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) InsertCourse(ctx context.Context, arg InsertCourseParams) error {
	_, err := q.db.Exec(ctx, insertCourse,
		arg.ID,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.Level,
		arg.ThumbnailUrl,
		arg.Status,
		arg.PriceAmountMinor,
		arg.PriceCurrency,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listCourseIDsByOwner = `-- name: ListCourseIDsByOwner :many
SELECT id FROM courseauthoring.courses WHERE owner_id = $1 ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListCourseIDsByOwner(ctx context.Context, ownerID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listCourseIDsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoursesByIDs = `-- name: ListCoursesByIDs :many
SELECT id, owner_id, title, description, level, thumbnail_url, status, price_amount_minor, price_currency, version, created_at, updated_at FROM courseauthoring.courses WHERE id = ANY($1::bigint[])
`

func (q *Queries) ListCoursesByIDs(ctx context.Context, ids []int64) ([]CourseauthoringCourse, error) {
	rows, err := q.db.Query(ctx, listCoursesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourseauthoringCourse
	for rows.Next() {
		var i CourseauthoringCourse
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.Level,
			&i.ThumbnailUrl,
			&i.Status,
			&i.PriceAmountMinor,
			&i.PriceCurrency,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLectureBlocks = `-- name: ListLectureBlocks :many
SELECT id, client_block_id, kind, position, payload
FROM courseauthoring.lecture_blocks WHERE lecture_id = $1 ORDER BY position
`

type ListLectureBlocksRow struct {
	ID            int64
	ClientBlockID string
	Kind          string
	Position      int32
	Payload       json.RawMessage
}

func (q *Queries) ListLectureBlocks(ctx context.Context, lectureID int64) ([]ListLectureBlocksRow, error) {
	rows, err := q.db.Query(ctx, listLectureBlocks, lectureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLectureBlocksRow
	for rows.Next() {
		var i ListLectureBlocksRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientBlockID,
			&i.Kind,
			&i.Position,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLecturesByCourseIDs = `-- name: ListLecturesByCourseIDs :many
SELECT l.id, l.course_id, l.section_id, l.title, l.free_preview, l.sort_order,
       EXISTS (SELECT 1 FROM courseauthoring.lecture_blocks b WHERE b.lecture_id = l.id AND b.kind = 'text')::bool AS has_text,
       EXISTS (SELECT 1 FROM courseauthoring.lecture_blocks b WHERE b.lecture_id = l.id AND b.kind = 'video')::bool AS has_video
FROM courseauthoring.lectures l
WHERE l.course_id = ANY($1::bigint[])
ORDER BY l.course_id, l.sort_order
`

type ListLecturesByCourseIDsRow struct {
	ID          int64
	CourseID    int64
	SectionID   *int64
	Title       string
	FreePreview bool
	SortOrder   int32
	HasText     bool
	HasVideo    bool
}

func (q *Queries) ListLecturesByCourseIDs(ctx context.Context, courseIds []int64) ([]ListLecturesByCourseIDsRow, error) {
	rows, err := q.db.Query(ctx, listLecturesByCourseIDs, courseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLecturesByCourseIDsRow
	for rows.Next() {
		var i ListLecturesByCourseIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.SectionID,
			&i.Title,
			&i.FreePreview,
			&i.SortOrder,
			&i.HasText,
			&i.HasVideo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionsByCourseIDs = `-- name: ListSectionsByCourseIDs :many
SELECT id, course_id, title, sort_order FROM courseauthoring.sections
WHERE course_id = ANY($1::bigint[])
ORDER BY course_id, sort_order
`

func (q *Queries) ListSectionsByCourseIDs(ctx context.Context, courseIds []int64) ([]CourseauthoringSection, error) {
	rows, err := q.db.Query(ctx, listSectionsByCourseIDs, courseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourseauthoringSection
	for rows.Next() {
		var i CourseauthoringSection
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCourse = `-- name: UpdateCourse :execrows
UPDATE courseauthoring.courses
SET title = $3, description = $4, level = $5, thumbnail_url = $6, status = $7,
    price_amount_minor = $8, price_currency = $9, updated_at = $10, version = version + 1
WHERE id = $1 AND version = $2
`

type UpdateCourseParams struct {
	ID               int64
	Version          int64
	Title            string
	Description      string
	Level            string
	ThumbnailUrl     string
	Status           string
	PriceAmountMinor int64
	PriceCurrency    string
	UpdatedAt        time.Time
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCourse,
		arg.ID,
		arg.Version,
		arg.Title,
		arg.Description,
		arg.Level,
		arg.ThumbnailUrl,
		arg.Status,
		arg.PriceAmountMinor,
		arg.PriceCurrency,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertLecture = `-- name: UpsertLecture :exec
INSERT INTO courseauthoring.lectures (id, course_id, section_id, title, free_preview, sort_order, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $7)
ON CONFLICT (id) DO UPDATE SET section_id = EXCLUDED.section_id, title = EXCLUDED.title,
  free_preview = EXCLUDED.free_preview, sort_order = EXCLUDED.sort_order, updated_at = EXCLUDED.updated_at
`

type UpsertLectureParams struct {
	ID          int64
	CourseID    int64
	SectionID   *int64
	Title       string
	FreePreview bool
	SortOrder   int32
	CreatedAt   time.Time
}

func (q *Queries) UpsertLecture(ctx context.Context, arg UpsertLectureParams) error {
	_, err := q.db.Exec(ctx, upsertLecture,
		arg.ID,
		arg.CourseID,
		arg.SectionID,
		arg.Title,
		arg.FreePreview,
		arg.SortOrder,
		arg.CreatedAt,
	)
	return err
}

const upsertLectureBlocks = `-- name: UpsertLectureBlocks :exec
INSERT INTO courseauthoring.lecture_blocks
  (id, course_id, lecture_id, client_block_id, kind, position, payload, created_at, updated_at)
SELECT (elem->>'id')::bigint, $1::bigint, $2::bigint,
       elem->>'client_block_id', elem->>'kind', (elem->>'position')::int, (elem->'payload')::jsonb,
       $3::timestamptz, $3::timestamptz
FROM jsonb_array_elements($4::jsonb) AS elem
ON CONFLICT (lecture_id, client_block_id) DO UPDATE SET
  kind = EXCLUDED.kind, position = EXCLUDED.position, payload = EXCLUDED.payload, updated_at = EXCLUDED.updated_at
`

type UpsertLectureBlocksParams struct {
	CourseID  int64
	LectureID int64
	Now       time.Time
	Blocks    json.RawMessage
}

// One jsonb array of {id, client_block_id, kind, position, payload}: sqlc cannot
// analyze a multi-array unnest(), and one bind value is one round trip either way.
func (q *Queries) UpsertLectureBlocks(ctx context.Context, arg UpsertLectureBlocksParams) error {
	_, err := q.db.Exec(ctx, upsertLectureBlocks,
		arg.CourseID,
		arg.LectureID,
		arg.Now,
		arg.Blocks,
	)
	return err
}

const upsertSection = `-- name: UpsertSection :exec
INSERT INTO courseauthoring.sections (id, course_id, title, sort_order)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, sort_order = EXCLUDED.sort_order
`

type UpsertSectionParams struct {
	ID        int64
	CourseID  int64
	Title     string
	SortOrder int32
}

func (q *Queries) UpsertSection(ctx context.Context, arg UpsertSectionParams) error {
	_, err := q.db.Exec(ctx, upsertSection,
		arg.ID,
		arg.CourseID,
		arg.Title,
		arg.SortOrder,
	)
	return err
}
