// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"
)

const applyLectureBlockOrder = `-- name: ApplyLectureBlockOrder :exec
UPDATE courseauthoring.lecture_blocks b
SET position = o.position - 1, updated_at = $1::timestamptz
FROM unnest($3::text[]) WITH ORDINALITY AS o(client_block_id, position)
WHERE b.lecture_id = $2::bigint
  AND b.client_block_id = o.client_block_id
  AND b.position IS DISTINCT FROM (o.position - 1)
`

type ApplyLectureBlockOrderParams struct {
	Now            time.Time
	LectureID      int64
	ClientBlockIds []string
}

// The position unique constraint is deferred, so permuting positions in one
// statement is allowed. Rows already in place are skipped.
func (q *Queries) ApplyLectureBlockOrder(ctx context.Context, arg ApplyLectureBlockOrderParams) error {
	_, err := q.db.Exec(ctx, applyLectureBlockOrder, arg.Now, arg.LectureID, arg.ClientBlockIds)
	return err
}

const bumpLectureContentRevision = `-- name: BumpLectureContentRevision :execrows
UPDATE courseauthoring.lectures
SET content_revision = content_revision + 1, updated_at = $3
WHERE id = $1 AND content_revision = $2
`

type BumpLectureContentRevisionParams struct {
	ID              int64
	ContentRevision int64
	UpdatedAt       time.Time
}

func (q *Queries) BumpLectureContentRevision(ctx context.Context, arg BumpLectureContentRevisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, bumpLectureContentRevision, arg.ID, arg.ContentRevision, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const copyVersionBlocks = `-- name: CopyVersionBlocks :exec
INSERT INTO courseauthoring.course_version_blocks (course_id, number, lecture_id, id, kind, position, client_block_id, payload)
SELECT course_id, $1::integer, lecture_id, id, kind, position, client_block_id, payload
FROM courseauthoring.lecture_blocks WHERE course_id = $2::bigint
`

type CopyVersionBlocksParams struct {
	Number   int32
	CourseID int64
}

func (q *Queries) CopyVersionBlocks(ctx context.Context, arg CopyVersionBlocksParams) error {
	_, err := q.db.Exec(ctx, copyVersionBlocks, arg.Number, arg.CourseID)
	return err
}

const copyVersionLectures = `-- name: CopyVersionLectures :exec
INSERT INTO courseauthoring.course_version_lectures (course_id, number, id, section_id, title, free_preview, sort_order)
SELECT course_id, $1::integer, id, section_id, title, free_preview, sort_order
FROM courseauthoring.lectures WHERE course_id = $2::bigint
`

type CopyVersionLecturesParams struct {
	Number   int32
	CourseID int64
}

func (q *Queries) CopyVersionLectures(ctx context.Context, arg CopyVersionLecturesParams) error {
	_, err := q.db.Exec(ctx, copyVersionLectures, arg.Number, arg.CourseID)
	return err
}

const copyVersionSections = `-- name: CopyVersionSections :exec
INSERT INTO courseauthoring.course_version_sections (course_id, number, id, title, sort_order)
SELECT course_id, $1::integer, id, title, sort_order
FROM courseauthoring.sections WHERE course_id = $2::bigint
`

type CopyVersionSectionsParams struct {
	Number   int32
	CourseID int64
}

func (q *Queries) CopyVersionSections(ctx context.Context, arg CopyVersionSectionsParams) error {
	_, err := q.db.Exec(ctx, copyVersionSections, arg.Number, arg.CourseID)
	return err
}

const countCategories = `-- name: CountCategories :one
SELECT count(*) FROM courseauthoring.categories WHERE id = ANY($1::bigint[])
`

func (q *Queries) CountCategories(ctx context.Context, ids []int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCategories, ids)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCategory = `-- name: DeleteCategory :execrows
DELETE FROM courseauthoring.categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCourseCategories = `-- name: DeleteCourseCategories :exec
DELETE FROM courseauthoring.course_categories WHERE course_id = $1
`

func (q *Queries) DeleteCourseCategories(ctx context.Context, courseID int64) error {
	_, err := q.db.Exec(ctx, deleteCourseCategories, courseID)
	return err
}

const deleteLectureBlocks = `-- name: DeleteLectureBlocks :exec
DELETE FROM courseauthoring.lecture_blocks WHERE lecture_id = $1
`

func (q *Queries) DeleteLectureBlocks(ctx context.Context, lectureID int64) error {
	_, err := q.db.Exec(ctx, deleteLectureBlocks, lectureID)
	return err
}

const deleteLectureBlocksByClientIDs = `-- name: DeleteLectureBlocksByClientIDs :exec
DELETE FROM courseauthoring.lecture_blocks
WHERE lecture_id = $1 AND client_block_id = ANY($2::text[])
`

type DeleteLectureBlocksByClientIDsParams struct {
	LectureID      int64
	ClientBlockIds []string
}

func (q *Queries) DeleteLectureBlocksByClientIDs(ctx context.Context, arg DeleteLectureBlocksByClientIDsParams) error {
	_, err := q.db.Exec(ctx, deleteLectureBlocksByClientIDs, arg.LectureID, arg.ClientBlockIds)
	return err
}

const deleteLecturesNotIn = `-- name: DeleteLecturesNotIn :exec
DELETE FROM courseauthoring.lectures
WHERE course_id = $1 AND NOT (id = ANY($2::bigint[]))
`

type DeleteLecturesNotInParams struct {
	CourseID int64
	Keep     []int64
}

func (q *Queries) DeleteLecturesNotIn(ctx context.Context, arg DeleteLecturesNotInParams) error {
	_, err := q.db.Exec(ctx, deleteLecturesNotIn, arg.CourseID, arg.Keep)
	return err
}

const deleteSectionsNotIn = `-- name: DeleteSectionsNotIn :exec
DELETE FROM courseauthoring.sections
WHERE course_id = $1 AND NOT (id = ANY($2::bigint[]))
`

type DeleteSectionsNotInParams struct {
	CourseID int64
	Keep     []int64
}

func (q *Queries) DeleteSectionsNotIn(ctx context.Context, arg DeleteSectionsNotInParams) error {
	_, err := q.db.Exec(ctx, deleteSectionsNotIn, arg.CourseID, arg.Keep)
	return err
}

const deleteSubmittedAssessments = `-- name: DeleteSubmittedAssessments :exec
DELETE FROM courseauthoring.course_submitted_assessments WHERE course_id = $1
`

func (q *Queries) DeleteSubmittedAssessments(ctx context.Context, courseID int64) error {
	_, err := q.db.Exec(ctx, deleteSubmittedAssessments, courseID)
	return err
}

const forceBumpLectureContentRevision = `-- name: ForceBumpLectureContentRevision :one
UPDATE courseauthoring.lectures
SET content_revision = content_revision + 1, updated_at = $2
WHERE id = $1
RETURNING content_revision
`

type ForceBumpLectureContentRevisionParams struct {
	ID        int64
	UpdatedAt time.Time
}

func (q *Queries) ForceBumpLectureContentRevision(ctx context.Context, arg ForceBumpLectureContentRevisionParams) (int64, error) {
	row := q.db.QueryRow(ctx, forceBumpLectureContentRevision, arg.ID, arg.UpdatedAt)
	var content_revision int64
	err := row.Scan(&content_revision)
	return content_revision, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, slug, created_at FROM courseauthoring.categories WHERE id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id int64) (CourseauthoringCategory, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i CourseauthoringCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getCourseVersion = `-- name: GetCourseVersion :one
SELECT course_id, number, title, description, level, thumbnail_url, price_amount_minor,
       price_currency, published_by, published_at, tags
FROM courseauthoring.course_versions WHERE course_id = $1 AND number = $2
`

type GetCourseVersionParams struct {
	CourseID int64
	Number   int32
}

type GetCourseVersionRow struct {
	CourseID         int64
	Number           int32
	Title            string
	Description      string
	Level            string
	ThumbnailUrl     string
	PriceAmountMinor int64
	PriceCurrency    string
	PublishedBy      int64
	PublishedAt      time.Time
	Tags             []string
}

func (q *Queries) GetCourseVersion(ctx context.Context, arg GetCourseVersionParams) (GetCourseVersionRow, error) {
	row := q.db.QueryRow(ctx, getCourseVersion, arg.CourseID, arg.Number)
	var i GetCourseVersionRow
	err := row.Scan(
		&i.CourseID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Level,
		&i.ThumbnailUrl,
		&i.PriceAmountMinor,
		&i.PriceCurrency,
		&i.PublishedBy,
		&i.PublishedAt,
		&i.Tags,
	)
	return i, err
}

const getLectureHeader = `-- name: GetLectureHeader :one
SELECT id, course_id, title, free_preview, content_revision
FROM courseauthoring.lectures WHERE course_id = $1 AND id = $2
`

type GetLectureHeaderParams struct {
	CourseID int64
	ID       int64
}

type GetLectureHeaderRow struct {
	ID              int64
	CourseID        int64
	Title           string
	FreePreview     bool
	ContentRevision int64
}

func (q *Queries) GetLectureHeader(ctx context.Context, arg GetLectureHeaderParams) (GetLectureHeaderRow, error) {
	row := q.db.QueryRow(ctx, getLectureHeader, arg.CourseID, arg.ID)
	var i GetLectureHeaderRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.FreePreview,
		&i.ContentRevision,
	)
	return i, err
}

const getLectureHeaderForUpdate = `-- name: GetLectureHeaderForUpdate :one
SELECT id, course_id, title, free_preview, content_revision
FROM courseauthoring.lectures WHERE course_id = $1 AND id = $2
FOR UPDATE
`

type GetLectureHeaderForUpdateParams struct {
	CourseID int64
	ID       int64
}

type GetLectureHeaderForUpdateRow struct {
	ID              int64
	CourseID        int64
	Title           string
	FreePreview     bool
	ContentRevision int64
}

func (q *Queries) GetLectureHeaderForUpdate(ctx context.Context, arg GetLectureHeaderForUpdateParams) (GetLectureHeaderForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getLectureHeaderForUpdate, arg.CourseID, arg.ID)
	var i GetLectureHeaderForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.FreePreview,
		&i.ContentRevision,
	)
	return i, err
}

const getVersionLecture = `-- name: GetVersionLecture :one
SELECT id, title, free_preview FROM courseauthoring.course_version_lectures
WHERE course_id = $1 AND number = $2 AND id = $3
`

type GetVersionLectureParams struct {
	CourseID int64
	Number   int32
	ID       int64
}

type GetVersionLectureRow struct {
	ID          int64
	Title       string
	FreePreview bool
}

func (q *Queries) GetVersionLecture(ctx context.Context, arg GetVersionLectureParams) (GetVersionLectureRow, error) {
	row := q.db.QueryRow(ctx, getVersionLecture, arg.CourseID, arg.Number, arg.ID)
	var i GetVersionLectureRow
	err := row.Scan(&i.ID, &i.Title, &i.FreePreview)
	return i, err
}

const insertCategory = `-- name: InsertCategory :exec
INSERT INTO courseauthoring.categories (id, name, slug, created_at) VALUES ($1, $2, $3, $4)
`

type InsertCategoryParams struct {
	ID        int64
	Name      string
	Slug      string
	CreatedAt time.Time
}

func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) error {
	_, err := q.db.Exec(ctx, insertCategory,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.CreatedAt,
	)
	return err
}

const insertCourse = `-- name: InsertCourse :exec
INSERT INTO courseauthoring.courses
  (id, owner_id, title, description, level, thumbnail_url, status, price_amount_minor, price_currency, version, created_at, updated_at, tags)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 1, $10, $11, $12)
`

type InsertCourseParams struct {
	ID               int64
	OwnerID          int64
	Title            string
	Description      string
	Level            string
	ThumbnailUrl     string
	Status           string
	PriceAmountMinor int64
	PriceCurrency    string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Tags             []string
}

func (q *Queries) InsertCourse(ctx context.Context, arg InsertCourseParams) error {
	_, err := q.db.Exec(ctx, insertCourse,
		arg.ID,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.Level,
		arg.ThumbnailUrl,
		arg.Status,
		arg.PriceAmountMinor,
		arg.PriceCurrency,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Tags,
	)
	return err
}

const insertCourseCategories = `-- name: InsertCourseCategories :exec
INSERT INTO courseauthoring.course_categories (course_id, category_id, position)
SELECT $1::bigint, t.category_id, (t.ord - 1)::integer
FROM unnest($2::bigint[]) WITH ORDINALITY AS t(category_id, ord)
`

type InsertCourseCategoriesParams struct {
	CourseID    int64
	CategoryIds []int64
}

func (q *Queries) InsertCourseCategories(ctx context.Context, arg InsertCourseCategoriesParams) error {
	_, err := q.db.Exec(ctx, insertCourseCategories, arg.CourseID, arg.CategoryIds)
	return err
}

const insertCourseReview = `-- name: InsertCourseReview :exec
INSERT INTO courseauthoring.course_reviews (id, course_id, actor_id, decision, note, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertCourseReviewParams struct {
	ID        int64
	CourseID  int64
	ActorID   int64
	Decision  string
	Note      string
	CreatedAt time.Time
}

func (q *Queries) InsertCourseReview(ctx context.Context, arg InsertCourseReviewParams) error {
	_, err := q.db.Exec(ctx, insertCourseReview,
		arg.ID,
		arg.CourseID,
		arg.ActorID,
		arg.Decision,
		arg.Note,
		arg.CreatedAt,
	)
	return err
}

const insertCourseVersion = `-- name: InsertCourseVersion :exec
INSERT INTO courseauthoring.course_versions
  (course_id, number, title, description, level, thumbnail_url, price_amount_minor, price_currency, published_by, published_at, tags)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertCourseVersionParams struct {
	CourseID         int64
	Number           int32
	Title            string
	Description      string
	Level            string
	ThumbnailUrl     string
	PriceAmountMinor int64
	PriceCurrency    string
	PublishedBy      int64
	PublishedAt      time.Time
	Tags             []string
}

func (q *Queries) InsertCourseVersion(ctx context.Context, arg InsertCourseVersionParams) error {
	_, err := q.db.Exec(ctx, insertCourseVersion,
		arg.CourseID,
		arg.Number,
		arg.Title,
		arg.Description,
		arg.Level,
		arg.ThumbnailUrl,
		arg.PriceAmountMinor,
		arg.PriceCurrency,
		arg.PublishedBy,
		arg.PublishedAt,
		arg.Tags,
	)
	return err
}

const insertSubmittedAssessments = `-- name: InsertSubmittedAssessments :exec
INSERT INTO courseauthoring.course_submitted_assessments (course_id, kind, assessment_id, revision)
SELECT $1, k, a, r
FROM ROWS FROM (unnest($2::text[]), unnest($3::bigint[]), unnest($4::integer[])) AS p(k, a, r)
`

type InsertSubmittedAssessmentsParams struct {
	CourseID      int64
	Kinds         []string
	AssessmentIds []int64
	Revisions     []int32
}

func (q *Queries) InsertSubmittedAssessments(ctx context.Context, arg InsertSubmittedAssessmentsParams) error {
	_, err := q.db.Exec(ctx, insertSubmittedAssessments,
		arg.CourseID,
		arg.Kinds,
		arg.AssessmentIds,
		arg.Revisions,
	)
	return err
}

const insertVersionAssessments = `-- name: InsertVersionAssessments :exec
INSERT INTO courseauthoring.course_version_assessments (course_id, number, kind, assessment_id, revision)
SELECT $1, $2, k, a, r
FROM ROWS FROM (unnest($3::text[]), unnest($4::bigint[]), unnest($5::integer[])) AS p(k, a, r)
`

type InsertVersionAssessmentsParams struct {
	CourseID      int64
	Number        int32
	Kinds         []string
	AssessmentIds []int64
	Revisions     []int32
}

func (q *Queries) InsertVersionAssessments(ctx context.Context, arg InsertVersionAssessmentsParams) error {
	_, err := q.db.Exec(ctx, insertVersionAssessments,
		arg.CourseID,
		arg.Number,
		arg.Kinds,
		arg.AssessmentIds,
		arg.Revisions,
	)
	return err
}

const insertVersionCategories = `-- name: InsertVersionCategories :exec
INSERT INTO courseauthoring.course_version_categories (course_id, number, category_id, position)
SELECT $1::bigint, $2::integer, t.category_id, (t.ord - 1)::integer
FROM unnest($3::bigint[]) WITH ORDINALITY AS t(category_id, ord)
`

type InsertVersionCategoriesParams struct {
	CourseID    int64
	Number      int32
	CategoryIds []int64
}

func (q *Queries) InsertVersionCategories(ctx context.Context, arg InsertVersionCategoriesParams) error {
	_, err := q.db.Exec(ctx, insertVersionCategories, arg.CourseID, arg.Number, arg.CategoryIds)
	return err
}

const listCategoriesByCourseIDs = `-- name: ListCategoriesByCourseIDs :many
SELECT cc.course_id, k.id, k.name, k.slug
FROM courseauthoring.course_categories cc
JOIN courseauthoring.categories k ON k.id = cc.category_id
WHERE cc.course_id = ANY($1::bigint[])
ORDER BY cc.course_id, cc.position
`

type ListCategoriesByCourseIDsRow struct {
	CourseID int64
	ID       int64
	Name     string
	Slug     string
}

func (q *Queries) ListCategoriesByCourseIDs(ctx context.Context, courseIds []int64) ([]ListCategoriesByCourseIDsRow, error) {
	rows, err := q.db.Query(ctx, listCategoriesByCourseIDs, courseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesByCourseIDsRow
	for rows.Next() {
		var i ListCategoriesByCourseIDsRow
		if err := rows.Scan(
			&i.CourseID,
			&i.ID,
			&i.Name,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesWithCounts = `-- name: ListCategoriesWithCounts :many
SELECT k.id, k.name, k.slug, k.created_at,
       (SELECT count(*) FROM courseauthoring.course_version_categories vc
        JOIN courseauthoring.courses c ON c.id = vc.course_id AND c.live_version = vc.number
        WHERE vc.category_id = k.id) AS course_count
FROM courseauthoring.categories k
ORDER BY lower(k.name), k.id
`

type ListCategoriesWithCountsRow struct {
	ID          int64
	Name        string
	Slug        string
	CreatedAt   time.Time
	CourseCount int64
}

func (q *Queries) ListCategoriesWithCounts(ctx context.Context) ([]ListCategoriesWithCountsRow, error) {
	rows, err := q.db.Query(ctx, listCategoriesWithCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesWithCountsRow
	for rows.Next() {
		var i ListCategoriesWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.CourseCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourseIDsByOwner = `-- name: ListCourseIDsByOwner :many
SELECT id FROM courseauthoring.courses WHERE owner_id = $1 ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListCourseIDsByOwner(ctx context.Context, ownerID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listCourseIDsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourseReviews = `-- name: ListCourseReviews :many
SELECT id, course_id, actor_id, decision, note, created_at
FROM courseauthoring.course_reviews WHERE course_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListCourseReviews(ctx context.Context, courseID int64) ([]CourseauthoringCourseReview, error) {
	rows, err := q.db.Query(ctx, listCourseReviews, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourseauthoringCourseReview
	for rows.Next() {
		var i CourseauthoringCourseReview
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.ActorID,
			&i.Decision,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourseVersions = `-- name: ListCourseVersions :many
SELECT number, published_by, published_at FROM courseauthoring.course_versions
WHERE course_id = $1 ORDER BY number DESC
`

type ListCourseVersionsRow struct {
	Number      int32
	PublishedBy int64
	PublishedAt time.Time
}

func (q *Queries) ListCourseVersions(ctx context.Context, courseID int64) ([]ListCourseVersionsRow, error) {
	rows, err := q.db.Query(ctx, listCourseVersions, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCourseVersionsRow
	for rows.Next() {
		var i ListCourseVersionsRow
		if err := rows.Scan(&i.Number, &i.PublishedBy, &i.PublishedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoursesByIDs = `-- name: ListCoursesByIDs :many
SELECT c.id, c.owner_id, c.title, c.description, c.level, c.thumbnail_url, c.status, c.price_amount_minor, c.price_currency, c.version, c.created_at, c.updated_at, c.submitted_at, c.reviewed_at, c.review_note, c.last_version, c.live_version, c.tags, v.published_at AS live_published_at
FROM courseauthoring.courses c
LEFT JOIN courseauthoring.course_versions v ON v.course_id = c.id AND v.number = c.live_version
WHERE c.id = ANY($1::bigint[])
`

type ListCoursesByIDsRow struct {
	ID               int64
	OwnerID          int64
	Title            string
	Description      string
	Level            string
	ThumbnailUrl     string
	Status           string
	PriceAmountMinor int64
	PriceCurrency    string
	Version          int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
	SubmittedAt      *time.Time
	ReviewedAt       *time.Time
	ReviewNote       string
	LastVersion      int32
	LiveVersion      *int32
	Tags             []string
	LivePublishedAt  *time.Time
}

func (q *Queries) ListCoursesByIDs(ctx context.Context, ids []int64) ([]ListCoursesByIDsRow, error) {
	rows, err := q.db.Query(ctx, listCoursesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCoursesByIDsRow
	for rows.Next() {
		var i ListCoursesByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.Level,
			&i.ThumbnailUrl,
			&i.Status,
			&i.PriceAmountMinor,
			&i.PriceCurrency,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubmittedAt,
			&i.ReviewedAt,
			&i.ReviewNote,
			&i.LastVersion,
			&i.LiveVersion,
			&i.Tags,
			&i.LivePublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInReviewCourseIDs = `-- name: ListInReviewCourseIDs :many
SELECT id FROM courseauthoring.courses WHERE status = 'in_review' ORDER BY submitted_at, id
`

func (q *Queries) ListInReviewCourseIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, listInReviewCourseIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLectureBlocks = `-- name: ListLectureBlocks :many
SELECT id, client_block_id, kind, position, payload
FROM courseauthoring.lecture_blocks WHERE lecture_id = $1 ORDER BY position
`

type ListLectureBlocksRow struct {
	ID            int64
	ClientBlockID string
	Kind          string
	Position      int32
	Payload       json.RawMessage
}

func (q *Queries) ListLectureBlocks(ctx context.Context, lectureID int64) ([]ListLectureBlocksRow, error) {
	rows, err := q.db.Query(ctx, listLectureBlocks, lectureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLectureBlocksRow
	for rows.Next() {
		var i ListLectureBlocksRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientBlockID,
			&i.Kind,
			&i.Position,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLecturesByCourseIDs = `-- name: ListLecturesByCourseIDs :many
SELECT l.id, l.course_id, l.section_id, l.title, l.free_preview, l.sort_order,
       EXISTS (SELECT 1 FROM courseauthoring.lecture_blocks b WHERE b.lecture_id = l.id AND b.kind = 'text')::bool AS has_text,
       EXISTS (SELECT 1 FROM courseauthoring.lecture_blocks b WHERE b.lecture_id = l.id AND b.kind = 'video')::bool AS has_video
FROM courseauthoring.lectures l
WHERE l.course_id = ANY($1::bigint[])
ORDER BY l.course_id, l.sort_order
`

type ListLecturesByCourseIDsRow struct {
	ID          int64
	CourseID    int64
	SectionID   *int64
	Title       string
	FreePreview bool
	SortOrder   int32
	HasText     bool
	HasVideo    bool
}

func (q *Queries) ListLecturesByCourseIDs(ctx context.Context, courseIds []int64) ([]ListLecturesByCourseIDsRow, error) {
	rows, err := q.db.Query(ctx, listLecturesByCourseIDs, courseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLecturesByCourseIDsRow
	for rows.Next() {
		var i ListLecturesByCourseIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.SectionID,
			&i.Title,
			&i.FreePreview,
			&i.SortOrder,
			&i.HasText,
			&i.HasVideo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveCategoriesByCourseIDs = `-- name: ListLiveCategoriesByCourseIDs :many
SELECT vc.course_id, k.id, k.name, k.slug
FROM courseauthoring.course_version_categories vc
JOIN courseauthoring.courses c ON c.id = vc.course_id AND c.live_version = vc.number
JOIN courseauthoring.categories k ON k.id = vc.category_id
WHERE vc.course_id = ANY($1::bigint[])
ORDER BY vc.course_id, vc.position
`

type ListLiveCategoriesByCourseIDsRow struct {
	CourseID int64
	ID       int64
	Name     string
	Slug     string
}

func (q *Queries) ListLiveCategoriesByCourseIDs(ctx context.Context, courseIds []int64) ([]ListLiveCategoriesByCourseIDsRow, error) {
	rows, err := q.db.Query(ctx, listLiveCategoriesByCourseIDs, courseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiveCategoriesByCourseIDsRow
	for rows.Next() {
		var i ListLiveCategoriesByCourseIDsRow
		if err := rows.Scan(
			&i.CourseID,
			&i.ID,
			&i.Name,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedCourses = `-- name: ListPublishedCourses :many
SELECT c.id, c.owner_id, v.title, v.description, v.level, v.thumbnail_url, v.tags,
       v.price_amount_minor, v.price_currency, c.created_at, v.published_at AS updated_at,
       (SELECT count(*) FROM courseauthoring.course_version_lectures l
        WHERE l.course_id = v.course_id AND l.number = v.number) AS lecture_count,
       (SELECT count(*) FROM courseauthoring.course_version_sections s
        WHERE s.course_id = v.course_id AND s.number = v.number) AS section_count,
       r.rank::real AS rank
FROM courseauthoring.courses c
JOIN courseauthoring.course_versions v ON v.course_id = c.id AND v.number = c.live_version
CROSS JOIN (
  SELECT websearch_to_tsquery('simple', $1::text) &&
         CASE WHEN $2::text = '' THEN ''::tsquery
              ELSE to_tsquery('simple', $2::text || ':*') END AS query
) s
CROSS JOIN LATERAL (
  SELECT CASE WHEN $3::bool THEN ts_rank(v.search, s.query) ELSE 0 END AS rank
) r
WHERE (NOT $3::bool OR v.search @@ s.query)
  AND ($4::text = '' OR v.level = $4::text)
  AND ($5::text = ''
       OR ($5::text = 'free' AND v.price_amount_minor = 0)
       OR ($5::text = 'paid' AND v.price_amount_minor > 0))
  AND ($6::text = '' OR v.tags @> ARRAY[$6::text])
  AND ($7::text = '' OR EXISTS (
        SELECT 1 FROM courseauthoring.course_version_categories vc
        JOIN courseauthoring.categories k ON k.id = vc.category_id
        WHERE vc.course_id = v.course_id AND vc.number = v.number AND k.slug = $7::text))
  AND ($8::bigint = 0
       OR (r.rank::real, c.id) < ($9::real, $8::bigint))
ORDER BY r.rank DESC, c.id DESC
LIMIT $10::integer
`

type ListPublishedCoursesParams struct {
	QHead     string
	QPrefix   string
	Search    bool
	Level     string
	Price     string
	Tag       string
	Category  string
	After     int64
	AfterRank float32
	RowLimit  int32
}

type ListPublishedCoursesRow struct {
	ID               int64
	OwnerID          int64
	Title            string
	Description      string
	Level            string
	ThumbnailUrl     string
	Tags             []string
	PriceAmountMinor int64
	PriceCurrency    string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	LectureCount     int64
	SectionCount     int64
	Rank             float32
}

// Lists live versions. updated_at is when the live version was published. With search set,
// rows match q_head as websearch text and q_prefix as the prefix of one more word, and are
// ordered by rank; otherwise rank is 0 and rows are ordered by ID alone.
func (q *Queries) ListPublishedCourses(ctx context.Context, arg ListPublishedCoursesParams) ([]ListPublishedCoursesRow, error) {
	rows, err := q.db.Query(ctx, listPublishedCourses,
		arg.QHead,
		arg.QPrefix,
		arg.Search,
		arg.Level,
		arg.Price,
		arg.Tag,
		arg.Category,
		arg.After,
		arg.AfterRank,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedCoursesRow
	for rows.Next() {
		var i ListPublishedCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.Level,
			&i.ThumbnailUrl,
			&i.Tags,
			&i.PriceAmountMinor,
			&i.PriceCurrency,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LectureCount,
			&i.SectionCount,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionsByCourseIDs = `-- name: ListSectionsByCourseIDs :many
SELECT id, course_id, title, sort_order FROM courseauthoring.sections
WHERE course_id = ANY($1::bigint[])
ORDER BY course_id, sort_order
`

func (q *Queries) ListSectionsByCourseIDs(ctx context.Context, courseIds []int64) ([]CourseauthoringSection, error) {
	rows, err := q.db.Query(ctx, listSectionsByCourseIDs, courseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourseauthoringSection
	for rows.Next() {
		var i CourseauthoringSection
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmittedAssessments = `-- name: ListSubmittedAssessments :many
SELECT kind, assessment_id, revision FROM courseauthoring.course_submitted_assessments
WHERE course_id = $1 ORDER BY kind, assessment_id
`

type ListSubmittedAssessmentsRow struct {
	Kind         string
	AssessmentID int64
	Revision     int32
}

func (q *Queries) ListSubmittedAssessments(ctx context.Context, courseID int64) ([]ListSubmittedAssessmentsRow, error) {
	rows, err := q.db.Query(ctx, listSubmittedAssessments, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubmittedAssessmentsRow
	for rows.Next() {
		var i ListSubmittedAssessmentsRow
		if err := rows.Scan(&i.Kind, &i.AssessmentID, &i.Revision); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersionAssessments = `-- name: ListVersionAssessments :many
SELECT kind, assessment_id, revision FROM courseauthoring.course_version_assessments
WHERE course_id = $1 AND number = $2 ORDER BY kind, assessment_id
`

type ListVersionAssessmentsParams struct {
	CourseID int64
	Number   int32
}

type ListVersionAssessmentsRow struct {
	Kind         string
	AssessmentID int64
	Revision     int32
}

func (q *Queries) ListVersionAssessments(ctx context.Context, arg ListVersionAssessmentsParams) ([]ListVersionAssessmentsRow, error) {
	rows, err := q.db.Query(ctx, listVersionAssessments, arg.CourseID, arg.Number)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVersionAssessmentsRow
	for rows.Next() {
		var i ListVersionAssessmentsRow
		if err := rows.Scan(&i.Kind, &i.AssessmentID, &i.Revision); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersionBlocks = `-- name: ListVersionBlocks :many
SELECT id, client_block_id, kind, position, payload FROM courseauthoring.course_version_blocks
WHERE course_id = $1 AND number = $2 AND lecture_id = $3 ORDER BY position
`

type ListVersionBlocksParams struct {
	CourseID  int64
	Number    int32
	LectureID int64
}

type ListVersionBlocksRow struct {
	ID            int64
	ClientBlockID string
	Kind          string
	Position      int32
	Payload       json.RawMessage
}

func (q *Queries) ListVersionBlocks(ctx context.Context, arg ListVersionBlocksParams) ([]ListVersionBlocksRow, error) {
	rows, err := q.db.Query(ctx, listVersionBlocks, arg.CourseID, arg.Number, arg.LectureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVersionBlocksRow
	for rows.Next() {
		var i ListVersionBlocksRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientBlockID,
			&i.Kind,
			&i.Position,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersionCategories = `-- name: ListVersionCategories :many
SELECT k.id, k.name, k.slug
FROM courseauthoring.course_version_categories vc
JOIN courseauthoring.categories k ON k.id = vc.category_id
WHERE vc.course_id = $1 AND vc.number = $2
ORDER BY vc.position
`

type ListVersionCategoriesParams struct {
	CourseID int64
	Number   int32
}

type ListVersionCategoriesRow struct {
	ID   int64
	Name string
	Slug string
}

func (q *Queries) ListVersionCategories(ctx context.Context, arg ListVersionCategoriesParams) ([]ListVersionCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listVersionCategories, arg.CourseID, arg.Number)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVersionCategoriesRow
	for rows.Next() {
		var i ListVersionCategoriesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersionLectures = `-- name: ListVersionLectures :many
SELECT l.id, l.section_id, l.title, l.free_preview, l.sort_order,
       EXISTS (SELECT 1 FROM courseauthoring.course_version_blocks b
               WHERE b.course_id = l.course_id AND b.number = l.number AND b.lecture_id = l.id AND b.kind = 'text')::bool AS has_text,
       EXISTS (SELECT 1 FROM courseauthoring.course_version_blocks b
               WHERE b.course_id = l.course_id AND b.number = l.number AND b.lecture_id = l.id AND b.kind = 'video')::bool AS has_video
FROM courseauthoring.course_version_lectures l
WHERE l.course_id = $1 AND l.number = $2
ORDER BY l.sort_order
`

type ListVersionLecturesParams struct {
	CourseID int64
	Number   int32
}

type ListVersionLecturesRow struct {
	ID          int64
	SectionID   *int64
	Title       string
	FreePreview bool
	SortOrder   int32
	HasText     bool
	HasVideo    bool
}

func (q *Queries) ListVersionLectures(ctx context.Context, arg ListVersionLecturesParams) ([]ListVersionLecturesRow, error) {
	rows, err := q.db.Query(ctx, listVersionLectures, arg.CourseID, arg.Number)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVersionLecturesRow
	for rows.Next() {
		var i ListVersionLecturesRow
		if err := rows.Scan(
			&i.ID,
			&i.SectionID,
			&i.Title,
			&i.FreePreview,
			&i.SortOrder,
			&i.HasText,
			&i.HasVideo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersionSections = `-- name: ListVersionSections :many
SELECT id, title, sort_order FROM courseauthoring.course_version_sections
WHERE course_id = $1 AND number = $2 ORDER BY sort_order
`

type ListVersionSectionsParams struct {
	CourseID int64
	Number   int32
}

type ListVersionSectionsRow struct {
	ID        int64
	Title     string
	SortOrder int32
}

func (q *Queries) ListVersionSections(ctx context.Context, arg ListVersionSectionsParams) ([]ListVersionSectionsRow, error) {
	rows, err := q.db.Query(ctx, listVersionSections, arg.CourseID, arg.Number)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVersionSectionsRow
	for rows.Next() {
		var i ListVersionSectionsRow
		if err := rows.Scan(&i.ID, &i.Title, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCourseForUpdate = `-- name: LockCourseForUpdate :one
SELECT id FROM courseauthoring.courses WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockCourseForUpdate(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockCourseForUpdate, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const updateCategory = `-- name: UpdateCategory :execrows
UPDATE courseauthoring.categories SET name = $2, slug = $3 WHERE id = $1
`

type UpdateCategoryParams struct {
	ID   int64
	Name string
	Slug string
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCategory, arg.ID, arg.Name, arg.Slug)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCourse = `-- name: UpdateCourse :execrows
UPDATE courseauthoring.courses
SET title = $3, description = $4, level = $5, thumbnail_url = $6, status = $7,
    price_amount_minor = $8, price_currency = $9, updated_at = $10,
    submitted_at = $11, reviewed_at = $12, review_note = $13, last_version = $14, live_version = $15,
    tags = $16, version = version + 1
WHERE id = $1 AND version = $2
`

type UpdateCourseParams struct {
	ID               int64
	Version          int64
	Title            string
	Description      string
	Level            string
	ThumbnailUrl     string
	Status           string
	PriceAmountMinor int64
	PriceCurrency    string
	UpdatedAt        time.Time
	SubmittedAt      *time.Time
	ReviewedAt       *time.Time
	ReviewNote       string
	LastVersion      int32
	LiveVersion      *int32
	Tags             []string
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCourse,
		arg.ID,
		arg.Version,
		arg.Title,
		arg.Description,
		arg.Level,
		arg.ThumbnailUrl,
		arg.Status,
		arg.PriceAmountMinor,
		arg.PriceCurrency,
		arg.UpdatedAt,
		arg.SubmittedAt,
		arg.ReviewedAt,
		arg.ReviewNote,
		arg.LastVersion,
		arg.LiveVersion,
		arg.Tags,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertLecture = `-- name: UpsertLecture :exec
INSERT INTO courseauthoring.lectures (id, course_id, section_id, title, free_preview, sort_order, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $7)
ON CONFLICT (id) DO UPDATE SET section_id = EXCLUDED.section_id, title = EXCLUDED.title,
  free_preview = EXCLUDED.free_preview, sort_order = EXCLUDED.sort_order, updated_at = EXCLUDED.updated_at
`

type UpsertLectureParams struct {
	ID          int64
	CourseID    int64
	SectionID   *int64
	Title       string
	FreePreview bool
	SortOrder   int32
	CreatedAt   time.Time
}

func (q *Queries) UpsertLecture(ctx context.Context, arg UpsertLectureParams) error {
	_, err := q.db.Exec(ctx, upsertLecture,
		arg.ID,
		arg.CourseID,
		arg.SectionID,
		arg.Title,
		arg.FreePreview,
		arg.SortOrder,
		arg.CreatedAt,
	)
	return err
}

const upsertLectureBlocks = `-- name: UpsertLectureBlocks :exec
INSERT INTO courseauthoring.lecture_blocks
  (id, course_id, lecture_id, client_block_id, kind, position, payload, created_at, updated_at)
SELECT (elem->>'id')::bigint, $1::bigint, $2::bigint,
       elem->>'client_block_id', elem->>'kind', (elem->>'position')::int, (elem->'payload')::jsonb,
       $3::timestamptz, $3::timestamptz
FROM jsonb_array_elements($4::jsonb) AS elem
ON CONFLICT (lecture_id, client_block_id) DO UPDATE SET
  kind = EXCLUDED.kind, position = EXCLUDED.position, payload = EXCLUDED.payload, updated_at = EXCLUDED.updated_at
`

type UpsertLectureBlocksParams struct {
	CourseID  int64
	LectureID int64
	Now       time.Time
	Blocks    json.RawMessage
}

// One jsonb array of {id, client_block_id, kind, position, payload}: sqlc cannot
// analyze a multi-array unnest(), and one bind value is one round trip either way.
func (q *Queries) UpsertLectureBlocks(ctx context.Context, arg UpsertLectureBlocksParams) error {
	_, err := q.db.Exec(ctx, upsertLectureBlocks,
		arg.CourseID,
		arg.LectureID,
		arg.Now,
		arg.Blocks,
	)
	return err
}

const upsertSection = `-- name: UpsertSection :exec
INSERT INTO courseauthoring.sections (id, course_id, title, sort_order)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, sort_order = EXCLUDED.sort_order
`

type UpsertSectionParams struct {
	ID        int64
	CourseID  int64
	Title     string
	SortOrder int32
}

func (q *Queries) UpsertSection(ctx context.Context, arg UpsertSectionParams) error {
	_, err := q.db.Exec(ctx, upsertSection,
		arg.ID,
		arg.CourseID,
		arg.Title,
		arg.SortOrder,
	)
	return err
}
