// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"
)

const applyPostBlockOrder = `-- name: ApplyPostBlockOrder :exec
UPDATE blog.post_blocks b
SET position = o.position - 1, updated_at = $1::timestamptz
FROM unnest($3::text[]) WITH ORDINALITY AS o(client_block_id, position)
WHERE b.post_id = $2::bigint
  AND b.client_block_id = o.client_block_id
  AND b.position IS DISTINCT FROM (o.position - 1)
`

type ApplyPostBlockOrderParams struct {
	Now            time.Time
	PostID         int64
	ClientBlockIds []string
}

// The position unique constraint is deferred, so permuting positions in one statement is allowed.
func (q *Queries) ApplyPostBlockOrder(ctx context.Context, arg ApplyPostBlockOrderParams) error {
	_, err := q.db.Exec(ctx, applyPostBlockOrder, arg.Now, arg.PostID, arg.ClientBlockIds)
	return err
}

const bumpPostContentRevision = `-- name: BumpPostContentRevision :execrows
UPDATE blog.posts SET content_revision = content_revision + 1
WHERE id = $1 AND content_revision = $2
`

type BumpPostContentRevisionParams struct {
	ID              int64
	ContentRevision int64
}

func (q *Queries) BumpPostContentRevision(ctx context.Context, arg BumpPostContentRevisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, bumpPostContentRevision, arg.ID, arg.ContentRevision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const copyPostVersionBlocks = `-- name: CopyPostVersionBlocks :exec
INSERT INTO blog.post_version_blocks (post_id, number, id, kind, position, client_block_id, payload)
SELECT post_id, $1::integer, id, kind, position, client_block_id, payload
FROM blog.post_blocks WHERE post_id = $2::bigint
`

type CopyPostVersionBlocksParams struct {
	Number int32
	PostID int64
}

func (q *Queries) CopyPostVersionBlocks(ctx context.Context, arg CopyPostVersionBlocksParams) error {
	_, err := q.db.Exec(ctx, copyPostVersionBlocks, arg.Number, arg.PostID)
	return err
}

const deletePostBlocks = `-- name: DeletePostBlocks :exec
DELETE FROM blog.post_blocks WHERE post_id = $1
`

func (q *Queries) DeletePostBlocks(ctx context.Context, postID int64) error {
	_, err := q.db.Exec(ctx, deletePostBlocks, postID)
	return err
}

const deletePostBlocksByClientIDs = `-- name: DeletePostBlocksByClientIDs :exec
DELETE FROM blog.post_blocks
WHERE post_id = $1 AND client_block_id = ANY($2::text[])
`

type DeletePostBlocksByClientIDsParams struct {
	PostID         int64
	ClientBlockIds []string
}

func (q *Queries) DeletePostBlocksByClientIDs(ctx context.Context, arg DeletePostBlocksByClientIDsParams) error {
	_, err := q.db.Exec(ctx, deletePostBlocksByClientIDs, arg.PostID, arg.ClientBlockIds)
	return err
}

const forceBumpPostContentRevision = `-- name: ForceBumpPostContentRevision :one
UPDATE blog.posts SET content_revision = content_revision + 1
WHERE id = $1
RETURNING content_revision
`

func (q *Queries) ForceBumpPostContentRevision(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, forceBumpPostContentRevision, id)
	var content_revision int64
	err := row.Scan(&content_revision)
	return content_revision, err
}

const getLivePost = `-- name: GetLivePost :one
SELECT p.id, p.author_id, p.slug, p.first_published_at, v.number, v.title, v.summary, v.cover_url,
       v.tags, v.reading_time_minutes, v.published_at
FROM blog.posts p
JOIN blog.post_versions v ON v.post_id = p.id AND v.number = p.live_version
WHERE p.id = $1
`

type GetLivePostRow struct {
	ID                 int64
	AuthorID           int64
	Slug               string
	FirstPublishedAt   *time.Time
	Number             int32
	Title              string
	Summary            string
	CoverUrl           string
	Tags               []string
	ReadingTimeMinutes int32
	PublishedAt        time.Time
}

func (q *Queries) GetLivePost(ctx context.Context, id int64) (GetLivePostRow, error) {
	row := q.db.QueryRow(ctx, getLivePost, id)
	var i GetLivePostRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Slug,
		&i.FirstPublishedAt,
		&i.Number,
		&i.Title,
		&i.Summary,
		&i.CoverUrl,
		&i.Tags,
		&i.ReadingTimeMinutes,
		&i.PublishedAt,
	)
	return i, err
}

const getPostContentHeader = `-- name: GetPostContentHeader :one
SELECT id, content_revision FROM blog.posts WHERE id = $1
`

type GetPostContentHeaderRow struct {
	ID              int64
	ContentRevision int64
}

func (q *Queries) GetPostContentHeader(ctx context.Context, id int64) (GetPostContentHeaderRow, error) {
	row := q.db.QueryRow(ctx, getPostContentHeader, id)
	var i GetPostContentHeaderRow
	err := row.Scan(&i.ID, &i.ContentRevision)
	return i, err
}

const getPostContentHeaderForUpdate = `-- name: GetPostContentHeaderForUpdate :one
SELECT id, content_revision FROM blog.posts WHERE id = $1 FOR UPDATE
`

type GetPostContentHeaderForUpdateRow struct {
	ID              int64
	ContentRevision int64
}

func (q *Queries) GetPostContentHeaderForUpdate(ctx context.Context, id int64) (GetPostContentHeaderForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getPostContentHeaderForUpdate, id)
	var i GetPostContentHeaderForUpdateRow
	err := row.Scan(&i.ID, &i.ContentRevision)
	return i, err
}

const getPostSlugOwner = `-- name: GetPostSlugOwner :one
SELECT post_id FROM blog.post_slugs WHERE slug = $1
`

func (q *Queries) GetPostSlugOwner(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRow(ctx, getPostSlugOwner, slug)
	var post_id int64
	err := row.Scan(&post_id)
	return post_id, err
}

const getPostVersion = `-- name: GetPostVersion :one
SELECT number, title, summary, cover_url, tags, reading_time_minutes, published_by, published_at
FROM blog.post_versions WHERE post_id = $1 AND number = $2
`

type GetPostVersionParams struct {
	PostID int64
	Number int32
}

type GetPostVersionRow struct {
	Number             int32
	Title              string
	Summary            string
	CoverUrl           string
	Tags               []string
	ReadingTimeMinutes int32
	PublishedBy        int64
	PublishedAt        time.Time
}

func (q *Queries) GetPostVersion(ctx context.Context, arg GetPostVersionParams) (GetPostVersionRow, error) {
	row := q.db.QueryRow(ctx, getPostVersion, arg.PostID, arg.Number)
	var i GetPostVersionRow
	err := row.Scan(
		&i.Number,
		&i.Title,
		&i.Summary,
		&i.CoverUrl,
		&i.Tags,
		&i.ReadingTimeMinutes,
		&i.PublishedBy,
		&i.PublishedAt,
	)
	return i, err
}

const insertPost = `-- name: InsertPost :exec
INSERT INTO blog.posts (id, author_id, title, summary, cover_url, tags, slug, status, version, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 1, $9, $10)
`

type InsertPostParams struct {
	ID        int64
	AuthorID  int64
	Title     string
	Summary   string
	CoverUrl  string
	Tags      []string
	Slug      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) InsertPost(ctx context.Context, arg InsertPostParams) error {
	_, err := q.db.Exec(ctx, insertPost,
		arg.ID,
		arg.AuthorID,
		arg.Title,
		arg.Summary,
		arg.CoverUrl,
		arg.Tags,
		arg.Slug,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertPostVersion = `-- name: InsertPostVersion :exec
INSERT INTO blog.post_versions
  (post_id, number, title, summary, cover_url, tags, reading_time_minutes, published_by, published_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertPostVersionParams struct {
	PostID             int64
	Number             int32
	Title              string
	Summary            string
	CoverUrl           string
	Tags               []string
	ReadingTimeMinutes int32
	PublishedBy        int64
	PublishedAt        time.Time
}

func (q *Queries) InsertPostVersion(ctx context.Context, arg InsertPostVersionParams) error {
	_, err := q.db.Exec(ctx, insertPostVersion,
		arg.PostID,
		arg.Number,
		arg.Title,
		arg.Summary,
		arg.CoverUrl,
		arg.Tags,
		arg.ReadingTimeMinutes,
		arg.PublishedBy,
		arg.PublishedAt,
	)
	return err
}

const listLiveIndex = `-- name: ListLiveIndex :many
SELECT p.id, p.slug, p.first_published_at, v.published_at
FROM blog.posts p
JOIN blog.post_versions v ON v.post_id = p.id AND v.number = p.live_version
WHERE $1::timestamptz IS NULL
   OR p.first_published_at < $1::timestamptz
   OR (p.first_published_at = $1::timestamptz AND p.id < $2::bigint)
ORDER BY p.first_published_at DESC, p.id DESC
LIMIT $3::integer
`

type ListLiveIndexParams struct {
	AfterAt  *time.Time
	AfterID  int64
	RowLimit int32
}

type ListLiveIndexRow struct {
	ID               int64
	Slug             string
	FirstPublishedAt *time.Time
	PublishedAt      time.Time
}

func (q *Queries) ListLiveIndex(ctx context.Context, arg ListLiveIndexParams) ([]ListLiveIndexRow, error) {
	rows, err := q.db.Query(ctx, listLiveIndex, arg.AfterAt, arg.AfterID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiveIndexRow
	for rows.Next() {
		var i ListLiveIndexRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.FirstPublishedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLivePosts = `-- name: ListLivePosts :many
SELECT p.id, p.author_id, p.slug, p.first_published_at, v.number, v.title, v.summary, v.cover_url,
       v.tags, v.reading_time_minutes, v.published_at
FROM blog.posts p
JOIN blog.post_versions v ON v.post_id = p.id AND v.number = p.live_version
WHERE ($1::text = '' OR v.tags @> ARRAY[$1::text])
  AND ($2::timestamptz IS NULL
       OR p.first_published_at < $2::timestamptz
       OR (p.first_published_at = $2::timestamptz AND p.id < $3::bigint))
ORDER BY p.first_published_at DESC, p.id DESC
LIMIT $4::integer
`

type ListLivePostsParams struct {
	Tag      string
	AfterAt  *time.Time
	AfterID  int64
	RowLimit int32
}

type ListLivePostsRow struct {
	ID                 int64
	AuthorID           int64
	Slug               string
	FirstPublishedAt   *time.Time
	Number             int32
	Title              string
	Summary            string
	CoverUrl           string
	Tags               []string
	ReadingTimeMinutes int32
	PublishedAt        time.Time
}

func (q *Queries) ListLivePosts(ctx context.Context, arg ListLivePostsParams) ([]ListLivePostsRow, error) {
	rows, err := q.db.Query(ctx, listLivePosts,
		arg.Tag,
		arg.AfterAt,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLivePostsRow
	for rows.Next() {
		var i ListLivePostsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Slug,
			&i.FirstPublishedAt,
			&i.Number,
			&i.Title,
			&i.Summary,
			&i.CoverUrl,
			&i.Tags,
			&i.ReadingTimeMinutes,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveTags = `-- name: ListLiveTags :many
SELECT t.tag::text AS tag, count(*)::integer AS post_count
FROM blog.posts p
JOIN blog.post_versions v ON v.post_id = p.id AND v.number = p.live_version
CROSS JOIN LATERAL unnest(v.tags) AS t(tag)
GROUP BY t.tag
ORDER BY post_count DESC, t.tag
`

type ListLiveTagsRow struct {
	Tag       string
	PostCount int32
}

func (q *Queries) ListLiveTags(ctx context.Context) ([]ListLiveTagsRow, error) {
	rows, err := q.db.Query(ctx, listLiveTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiveTagsRow
	for rows.Next() {
		var i ListLiveTagsRow
		if err := rows.Scan(&i.Tag, &i.PostCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostBlocks = `-- name: ListPostBlocks :many
SELECT id, client_block_id, kind, position, payload
FROM blog.post_blocks WHERE post_id = $1 ORDER BY position
`

type ListPostBlocksRow struct {
	ID            int64
	ClientBlockID string
	Kind          string
	Position      int32
	Payload       json.RawMessage
}

func (q *Queries) ListPostBlocks(ctx context.Context, postID int64) ([]ListPostBlocksRow, error) {
	rows, err := q.db.Query(ctx, listPostBlocks, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostBlocksRow
	for rows.Next() {
		var i ListPostBlocksRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientBlockID,
			&i.Kind,
			&i.Position,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostIDsByAuthor = `-- name: ListPostIDsByAuthor :many
SELECT id FROM blog.posts WHERE author_id = $1 ORDER BY id DESC
`

func (q *Queries) ListPostIDsByAuthor(ctx context.Context, authorID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listPostIDsByAuthor, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostVersionBlocks = `-- name: ListPostVersionBlocks :many
SELECT id, client_block_id, kind, position, payload FROM blog.post_version_blocks
WHERE post_id = $1 AND number = $2 ORDER BY position
`

type ListPostVersionBlocksParams struct {
	PostID int64
	Number int32
}

type ListPostVersionBlocksRow struct {
	ID            int64
	ClientBlockID string
	Kind          string
	Position      int32
	Payload       json.RawMessage
}

func (q *Queries) ListPostVersionBlocks(ctx context.Context, arg ListPostVersionBlocksParams) ([]ListPostVersionBlocksRow, error) {
	rows, err := q.db.Query(ctx, listPostVersionBlocks, arg.PostID, arg.Number)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostVersionBlocksRow
	for rows.Next() {
		var i ListPostVersionBlocksRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientBlockID,
			&i.Kind,
			&i.Position,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostVersions = `-- name: ListPostVersions :many
SELECT number, published_by, published_at FROM blog.post_versions
WHERE post_id = $1 ORDER BY number DESC
`

type ListPostVersionsRow struct {
	Number      int32
	PublishedBy int64
	PublishedAt time.Time
}

func (q *Queries) ListPostVersions(ctx context.Context, postID int64) ([]ListPostVersionsRow, error) {
	rows, err := q.db.Query(ctx, listPostVersions, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostVersionsRow
	for rows.Next() {
		var i ListPostVersionsRow
		if err := rows.Scan(&i.Number, &i.PublishedBy, &i.PublishedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByIDs = `-- name: ListPostsByIDs :many
SELECT p.id, p.author_id, p.title, p.summary, p.cover_url, p.tags, p.slug, p.status,
       p.last_version, p.live_version, p.first_published_at, p.version, p.created_at, p.updated_at,
       v.published_at AS live_published_at
FROM blog.posts p
LEFT JOIN blog.post_versions v ON v.post_id = p.id AND v.number = p.live_version
WHERE p.id = ANY($1::bigint[])
ORDER BY p.id DESC
`

type ListPostsByIDsRow struct {
	ID               int64
	AuthorID         int64
	Title            string
	Summary          string
	CoverUrl         string
	Tags             []string
	Slug             string
	Status           string
	LastVersion      int32
	LiveVersion      *int32
	FirstPublishedAt *time.Time
	Version          int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
	LivePublishedAt  *time.Time
}

func (q *Queries) ListPostsByIDs(ctx context.Context, ids []int64) ([]ListPostsByIDsRow, error) {
	rows, err := q.db.Query(ctx, listPostsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsByIDsRow
	for rows.Next() {
		var i ListPostsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Summary,
			&i.CoverUrl,
			&i.Tags,
			&i.Slug,
			&i.Status,
			&i.LastVersion,
			&i.LiveVersion,
			&i.FirstPublishedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LivePublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reservePostSlug = `-- name: ReservePostSlug :exec
INSERT INTO blog.post_slugs (slug, post_id, created_at) VALUES ($1, $2, $3)
ON CONFLICT (slug) DO NOTHING
`

type ReservePostSlugParams struct {
	Slug      string
	PostID    int64
	CreatedAt time.Time
}

func (q *Queries) ReservePostSlug(ctx context.Context, arg ReservePostSlugParams) error {
	_, err := q.db.Exec(ctx, reservePostSlug, arg.Slug, arg.PostID, arg.CreatedAt)
	return err
}

const updatePost = `-- name: UpdatePost :execrows
UPDATE blog.posts
SET title = $3, summary = $4, cover_url = $5, tags = $6, slug = $7, status = $8,
    last_version = $9, live_version = $10, first_published_at = $11, updated_at = $12,
    version = version + 1
WHERE id = $1 AND version = $2
`

type UpdatePostParams struct {
	ID               int64
	Version          int64
	Title            string
	Summary          string
	CoverUrl         string
	Tags             []string
	Slug             string
	Status           string
	LastVersion      int32
	LiveVersion      *int32
	FirstPublishedAt *time.Time
	UpdatedAt        time.Time
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePost,
		arg.ID,
		arg.Version,
		arg.Title,
		arg.Summary,
		arg.CoverUrl,
		arg.Tags,
		arg.Slug,
		arg.Status,
		arg.LastVersion,
		arg.LiveVersion,
		arg.FirstPublishedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPostBlocks = `-- name: UpsertPostBlocks :exec
INSERT INTO blog.post_blocks (id, post_id, client_block_id, kind, position, payload, created_at, updated_at)
SELECT (elem->>'id')::bigint, $1::bigint,
       elem->>'client_block_id', elem->>'kind', (elem->>'position')::int, (elem->'payload')::jsonb,
       $2::timestamptz, $2::timestamptz
FROM jsonb_array_elements($3::jsonb) AS elem
ON CONFLICT (post_id, client_block_id) DO UPDATE SET
  kind = EXCLUDED.kind, position = EXCLUDED.position, payload = EXCLUDED.payload, updated_at = EXCLUDED.updated_at
`

type UpsertPostBlocksParams struct {
	PostID int64
	Now    time.Time
	Blocks json.RawMessage
}

// One jsonb array of {id, client_block_id, kind, position, payload}, as for lecture blocks.
func (q *Queries) UpsertPostBlocks(ctx context.Context, arg UpsertPostBlocksParams) error {
	_, err := q.db.Exec(ctx, upsertPostBlocks, arg.PostID, arg.Now, arg.Blocks)
	return err
}
