// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"
)

const deleteQuiz = `-- name: DeleteQuiz :exec
DELETE FROM assessment.quizzes WHERE id = $1
`

func (q *Queries) DeleteQuiz(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteQuiz, id)
	return err
}

const findQuizAttemptByKey = `-- name: FindQuizAttemptByKey :one
SELECT id FROM assessment.quiz_attempts
WHERE quiz_id = $1 AND user_id = $2 AND idempotency_key = $3
`

type FindQuizAttemptByKeyParams struct {
	QuizID         int64
	UserID         int64
	IdempotencyKey *string
}

func (q *Queries) FindQuizAttemptByKey(ctx context.Context, arg FindQuizAttemptByKeyParams) (int64, error) {
	row := q.db.QueryRow(ctx, findQuizAttemptByKey, arg.QuizID, arg.UserID, arg.IdempotencyKey)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getQuiz = `-- name: GetQuiz :one
SELECT id, course_id, lecture_id, position, questions, created_at, updated_at FROM assessment.quizzes WHERE id = $1
`

func (q *Queries) GetQuiz(ctx context.Context, id int64) (AssessmentQuiz, error) {
	row := q.db.QueryRow(ctx, getQuiz, id)
	var i AssessmentQuiz
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.LectureID,
		&i.Position,
		&i.Questions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertQuiz = `-- name: InsertQuiz :exec
INSERT INTO assessment.quizzes (id, course_id, lecture_id, position, questions, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertQuizParams struct {
	ID        int64
	CourseID  int64
	LectureID int64
	Position  int32
	Questions json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) InsertQuiz(ctx context.Context, arg InsertQuizParams) error {
	_, err := q.db.Exec(ctx, insertQuiz,
		arg.ID,
		arg.CourseID,
		arg.LectureID,
		arg.Position,
		arg.Questions,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertQuizAttempt = `-- name: InsertQuizAttempt :one
INSERT INTO assessment.quiz_attempts (id, quiz_id, user_id, answers, idempotency_key, submitted_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (quiz_id, user_id, idempotency_key) WHERE idempotency_key IS NOT NULL DO NOTHING
RETURNING id
`

type InsertQuizAttemptParams struct {
	ID             int64
	QuizID         int64
	UserID         int64
	Answers        json.RawMessage
	IdempotencyKey *string
	SubmittedAt    time.Time
}

// Returns no row when an attempt with the same quiz, user and key exists.
func (q *Queries) InsertQuizAttempt(ctx context.Context, arg InsertQuizAttemptParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertQuizAttempt,
		arg.ID,
		arg.QuizID,
		arg.UserID,
		arg.Answers,
		arg.IdempotencyKey,
		arg.SubmittedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listQuizLectures = `-- name: ListQuizLectures :many
SELECT id, lecture_id FROM assessment.quizzes
WHERE course_id = $1 AND id = ANY($2::bigint[])
`

type ListQuizLecturesParams struct {
	CourseID int64
	QuizIds  []int64
}

type ListQuizLecturesRow struct {
	ID        int64
	LectureID int64
}

func (q *Queries) ListQuizLectures(ctx context.Context, arg ListQuizLecturesParams) ([]ListQuizLecturesRow, error) {
	rows, err := q.db.Query(ctx, listQuizLectures, arg.CourseID, arg.QuizIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuizLecturesRow
	for rows.Next() {
		var i ListQuizLecturesRow
		if err := rows.Scan(&i.ID, &i.LectureID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuizzesByLecture = `-- name: ListQuizzesByLecture :many
SELECT id, course_id, lecture_id, position, questions, created_at, updated_at FROM assessment.quizzes
WHERE course_id = $1 AND lecture_id = $2
ORDER BY position, id
`

type ListQuizzesByLectureParams struct {
	CourseID  int64
	LectureID int64
}

func (q *Queries) ListQuizzesByLecture(ctx context.Context, arg ListQuizzesByLectureParams) ([]AssessmentQuiz, error) {
	rows, err := q.db.Query(ctx, listQuizzesByLecture, arg.CourseID, arg.LectureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssessmentQuiz
	for rows.Next() {
		var i AssessmentQuiz
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.LectureID,
			&i.Position,
			&i.Questions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceQuiz = `-- name: ReplaceQuiz :execrows
UPDATE assessment.quizzes SET position = $2, questions = $3, updated_at = $4 WHERE id = $1
`

type ReplaceQuizParams struct {
	ID        int64
	Position  int32
	Questions json.RawMessage
	UpdatedAt time.Time
}

func (q *Queries) ReplaceQuiz(ctx context.Context, arg ReplaceQuizParams) (int64, error) {
	result, err := q.db.Exec(ctx, replaceQuiz,
		arg.ID,
		arg.Position,
		arg.Questions,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
