// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"
)

const getCourseProgress = `-- name: GetCourseProgress :one
SELECT course_id, user_id, last_lecture_id, updated_at FROM progress.course_progress WHERE course_id = $1 AND user_id = $2
`

type GetCourseProgressParams struct {
	CourseID int64
	UserID   int64
}

func (q *Queries) GetCourseProgress(ctx context.Context, arg GetCourseProgressParams) (ProgressCourseProgress, error) {
	row := q.db.QueryRow(ctx, getCourseProgress, arg.CourseID, arg.UserID)
	var i ProgressCourseProgress
	err := row.Scan(
		&i.CourseID,
		&i.UserID,
		&i.LastLectureID,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivityDaysByUser = `-- name: ListActivityDaysByUser :many
SELECT to_char(updated_at AT TIME ZONE 'UTC', 'YYYY-MM-DD')::text AS day,
       count(DISTINCT lecture_id)::bigint AS lecture_count
FROM progress.lecture_progress
WHERE user_id = $1
GROUP BY day
ORDER BY day DESC
`

type ListActivityDaysByUserRow struct {
	Day          string
	LectureCount int64
}

// Buckets by UTC date regardless of the session time zone.
func (q *Queries) ListActivityDaysByUser(ctx context.Context, userID int64) ([]ListActivityDaysByUserRow, error) {
	rows, err := q.db.Query(ctx, listActivityDaysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivityDaysByUserRow
	for rows.Next() {
		var i ListActivityDaysByUserRow
		if err := rows.Scan(&i.Day, &i.LectureCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourseProgressByUser = `-- name: ListCourseProgressByUser :many
SELECT course_id, user_id, last_lecture_id, updated_at FROM progress.course_progress
WHERE user_id = $1
ORDER BY updated_at DESC, course_id
`

func (q *Queries) ListCourseProgressByUser(ctx context.Context, userID int64) ([]ProgressCourseProgress, error) {
	rows, err := q.db.Query(ctx, listCourseProgressByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProgressCourseProgress
	for rows.Next() {
		var i ProgressCourseProgress
		if err := rows.Scan(
			&i.CourseID,
			&i.UserID,
			&i.LastLectureID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLectureProgressByUser = `-- name: ListLectureProgressByUser :many
SELECT course_id, user_id, lecture_id, state, position_ms, updated_at FROM progress.lecture_progress
WHERE user_id = $1
ORDER BY course_id, lecture_id
`

func (q *Queries) ListLectureProgressByUser(ctx context.Context, userID int64) ([]ProgressLectureProgress, error) {
	rows, err := q.db.Query(ctx, listLectureProgressByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProgressLectureProgress
	for rows.Next() {
		var i ProgressLectureProgress
		if err := rows.Scan(
			&i.CourseID,
			&i.UserID,
			&i.LectureID,
			&i.State,
			&i.PositionMs,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLectureProgressForCourse = `-- name: ListLectureProgressForCourse :many
SELECT course_id, user_id, lecture_id, state, position_ms, updated_at FROM progress.lecture_progress
WHERE course_id = $1 AND user_id = $2
ORDER BY lecture_id
`

type ListLectureProgressForCourseParams struct {
	CourseID int64
	UserID   int64
}

func (q *Queries) ListLectureProgressForCourse(ctx context.Context, arg ListLectureProgressForCourseParams) ([]ProgressLectureProgress, error) {
	rows, err := q.db.Query(ctx, listLectureProgressForCourse, arg.CourseID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProgressLectureProgress
	for rows.Next() {
		var i ProgressLectureProgress
		if err := rows.Scan(
			&i.CourseID,
			&i.UserID,
			&i.LectureID,
			&i.State,
			&i.PositionMs,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCourseProgress = `-- name: UpsertCourseProgress :exec
INSERT INTO progress.course_progress (course_id, user_id, last_lecture_id, updated_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (course_id, user_id) DO UPDATE SET
  last_lecture_id = EXCLUDED.last_lecture_id,
  updated_at = EXCLUDED.updated_at
`

type UpsertCourseProgressParams struct {
	CourseID      int64
	UserID        int64
	LastLectureID int64
	UpdatedAt     time.Time
}

func (q *Queries) UpsertCourseProgress(ctx context.Context, arg UpsertCourseProgressParams) error {
	_, err := q.db.Exec(ctx, upsertCourseProgress,
		arg.CourseID,
		arg.UserID,
		arg.LastLectureID,
		arg.UpdatedAt,
	)
	return err
}

const upsertLectureProgress = `-- name: UpsertLectureProgress :one
INSERT INTO progress.lecture_progress AS lp (course_id, user_id, lecture_id, state, position_ms, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (course_id, user_id, lecture_id) DO UPDATE SET
  state = EXCLUDED.state,
  position_ms = EXCLUDED.position_ms,
  updated_at = EXCLUDED.updated_at
WHERE lp.state <> 'completed' OR EXCLUDED.state = 'completed'
RETURNING lecture_id
`

type UpsertLectureProgressParams struct {
	CourseID   int64
	UserID     int64
	LectureID  int64
	State      string
	PositionMs int64
	UpdatedAt  time.Time
}

// Returns no row when a completed lecture rejects an in_progress write.
func (q *Queries) UpsertLectureProgress(ctx context.Context, arg UpsertLectureProgressParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertLectureProgress,
		arg.CourseID,
		arg.UserID,
		arg.LectureID,
		arg.State,
		arg.PositionMs,
		arg.UpdatedAt,
	)
	var lecture_id int64
	err := row.Scan(&lecture_id)
	return lecture_id, err
}
