// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"
)

const deleteAsset = `-- name: DeleteAsset :exec
DELETE FROM media.assets WHERE id = $1
`

func (q *Queries) DeleteAsset(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAsset, id)
	return err
}

const getAsset = `-- name: GetAsset :one
SELECT id, course_id, kind, created_by, created_at FROM media.assets WHERE id = $1
`

func (q *Queries) GetAsset(ctx context.Context, id int64) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, getAsset, id)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Kind,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertAsset = `-- name: InsertAsset :exec
INSERT INTO media.assets (id, course_id, kind, created_by, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAssetParams struct {
	ID        int64
	CourseID  int64
	Kind      string
	CreatedBy int64
	CreatedAt time.Time
}

func (q *Queries) InsertAsset(ctx context.Context, arg InsertAssetParams) error {
	_, err := q.db.Exec(ctx, insertAsset,
		arg.ID,
		arg.CourseID,
		arg.Kind,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const listAssetKindsInCourse = `-- name: ListAssetKindsInCourse :many
SELECT id, kind FROM media.assets
WHERE course_id = $1 AND id = ANY($2::bigint[])
`

type ListAssetKindsInCourseParams struct {
	CourseID int64
	Ids      []int64
}

type ListAssetKindsInCourseRow struct {
	ID   int64
	Kind string
}

func (q *Queries) ListAssetKindsInCourse(ctx context.Context, arg ListAssetKindsInCourseParams) ([]ListAssetKindsInCourseRow, error) {
	rows, err := q.db.Query(ctx, listAssetKindsInCourse, arg.CourseID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetKindsInCourseRow
	for rows.Next() {
		var i ListAssetKindsInCourseRow
		if err := rows.Scan(&i.ID, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
