// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"
)

const countPaidPurchases = `-- name: CountPaidPurchases :one
SELECT count(*) FROM payment.purchases WHERE user_id = $1 AND course_id = $2 AND status = 'paid'
`

type CountPaidPurchasesParams struct {
	UserID   int64
	CourseID int64
}

func (q *Queries) CountPaidPurchases(ctx context.Context, arg CountPaidPurchasesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPaidPurchases, arg.UserID, arg.CourseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPurchase = `-- name: GetPurchase :one
SELECT id, user_id, course_id, amount_minor, currency, gateway, gateway_ref, gateway_txn, status, created_at, settled_at, granted_at, version FROM payment.purchases WHERE id = $1
`

func (q *Queries) GetPurchase(ctx context.Context, id int64) (PaymentPurchase, error) {
	row := q.db.QueryRow(ctx, getPurchase, id)
	var i PaymentPurchase
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.AmountMinor,
		&i.Currency,
		&i.Gateway,
		&i.GatewayRef,
		&i.GatewayTxn,
		&i.Status,
		&i.CreatedAt,
		&i.SettledAt,
		&i.GrantedAt,
		&i.Version,
	)
	return i, err
}

const insertPurchase = `-- name: InsertPurchase :exec
INSERT INTO payment.purchases
  (id, user_id, course_id, amount_minor, currency, gateway, gateway_ref, gateway_txn, status,
   created_at, settled_at, granted_at, version)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, 1)
`

type InsertPurchaseParams struct {
	ID          int64
	UserID      int64
	CourseID    int64
	AmountMinor int64
	Currency    string
	Gateway     string
	GatewayRef  string
	GatewayTxn  string
	Status      string
	CreatedAt   time.Time
	SettledAt   *time.Time
	GrantedAt   *time.Time
}

func (q *Queries) InsertPurchase(ctx context.Context, arg InsertPurchaseParams) error {
	_, err := q.db.Exec(ctx, insertPurchase,
		arg.ID,
		arg.UserID,
		arg.CourseID,
		arg.AmountMinor,
		arg.Currency,
		arg.Gateway,
		arg.GatewayRef,
		arg.GatewayTxn,
		arg.Status,
		arg.CreatedAt,
		arg.SettledAt,
		arg.GrantedAt,
	)
	return err
}

const listUnsettledPurchases = `-- name: ListUnsettledPurchases :many
SELECT id, user_id, course_id, amount_minor, currency, gateway, gateway_ref, gateway_txn, status, created_at, settled_at, granted_at, version FROM payment.purchases
WHERE id > $1::bigint
  AND ((status = 'pending' AND created_at < $2::timestamptz)
       OR (status = 'paid' AND granted_at IS NULL))
ORDER BY id
LIMIT $3::bigint
`

type ListUnsettledPurchasesParams struct {
	AfterID       int64
	PendingBefore time.Time
	PageLimit     int64
}

func (q *Queries) ListUnsettledPurchases(ctx context.Context, arg ListUnsettledPurchasesParams) ([]PaymentPurchase, error) {
	rows, err := q.db.Query(ctx, listUnsettledPurchases, arg.AfterID, arg.PendingBefore, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentPurchase
	for rows.Next() {
		var i PaymentPurchase
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CourseID,
			&i.AmountMinor,
			&i.Currency,
			&i.Gateway,
			&i.GatewayRef,
			&i.GatewayTxn,
			&i.Status,
			&i.CreatedAt,
			&i.SettledAt,
			&i.GrantedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePurchase = `-- name: UpdatePurchase :execrows
UPDATE payment.purchases
SET gateway_txn = $3, status = $4, settled_at = $5, granted_at = $6, version = version + 1
WHERE id = $1 AND version = $2
`

type UpdatePurchaseParams struct {
	ID         int64
	Version    int64
	GatewayTxn string
	Status     string
	SettledAt  *time.Time
	GrantedAt  *time.Time
}

func (q *Queries) UpdatePurchase(ctx context.Context, arg UpdatePurchaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePurchase,
		arg.ID,
		arg.Version,
		arg.GatewayTxn,
		arg.Status,
		arg.SettledAt,
		arg.GrantedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
