// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"
)

const countActiveEnrollmentsByCourse = `-- name: CountActiveEnrollmentsByCourse :one
SELECT count(*) FROM enrollment.enrollments WHERE course_id = $1 AND status = 'active'
`

func (q *Queries) CountActiveEnrollmentsByCourse(ctx context.Context, courseID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveEnrollmentsByCourse, courseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getEnrollment = `-- name: GetEnrollment :one
SELECT id, course_id, user_id, status, cancel_reason, enrolled_at, canceled_at, version FROM enrollment.enrollments WHERE course_id = $1 AND user_id = $2
`

type GetEnrollmentParams struct {
	CourseID int64
	UserID   int64
}

func (q *Queries) GetEnrollment(ctx context.Context, arg GetEnrollmentParams) (EnrollmentEnrollment, error) {
	row := q.db.QueryRow(ctx, getEnrollment, arg.CourseID, arg.UserID)
	var i EnrollmentEnrollment
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.UserID,
		&i.Status,
		&i.CancelReason,
		&i.EnrolledAt,
		&i.CanceledAt,
		&i.Version,
	)
	return i, err
}

const insertEnrollment = `-- name: InsertEnrollment :exec
INSERT INTO enrollment.enrollments
  (id, course_id, user_id, status, cancel_reason, enrolled_at, canceled_at, version)
VALUES ($1, $2, $3, $4, $5, $6, $7, 1)
`

type InsertEnrollmentParams struct {
	ID           int64
	CourseID     int64
	UserID       int64
	Status       string
	CancelReason string
	EnrolledAt   time.Time
	CanceledAt   *time.Time
}

func (q *Queries) InsertEnrollment(ctx context.Context, arg InsertEnrollmentParams) error {
	_, err := q.db.Exec(ctx, insertEnrollment,
		arg.ID,
		arg.CourseID,
		arg.UserID,
		arg.Status,
		arg.CancelReason,
		arg.EnrolledAt,
		arg.CanceledAt,
	)
	return err
}

const listActiveEnrollmentsByCourse = `-- name: ListActiveEnrollmentsByCourse :many
SELECT id, course_id, user_id, status, cancel_reason, enrolled_at, canceled_at, version FROM enrollment.enrollments
WHERE course_id = $1 AND status = 'active'
ORDER BY enrolled_at, id
LIMIT $3::bigint OFFSET $2::bigint
`

type ListActiveEnrollmentsByCourseParams struct {
	CourseID   int64
	PageOffset int64
	PageLimit  int64
}

func (q *Queries) ListActiveEnrollmentsByCourse(ctx context.Context, arg ListActiveEnrollmentsByCourseParams) ([]EnrollmentEnrollment, error) {
	rows, err := q.db.Query(ctx, listActiveEnrollmentsByCourse, arg.CourseID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnrollmentEnrollment
	for rows.Next() {
		var i EnrollmentEnrollment
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.UserID,
			&i.Status,
			&i.CancelReason,
			&i.EnrolledAt,
			&i.CanceledAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveEnrollmentsByUser = `-- name: ListActiveEnrollmentsByUser :many
SELECT id, course_id, user_id, status, cancel_reason, enrolled_at, canceled_at, version FROM enrollment.enrollments
WHERE user_id = $1 AND status = 'active'
ORDER BY enrolled_at DESC, id DESC
`

func (q *Queries) ListActiveEnrollmentsByUser(ctx context.Context, userID int64) ([]EnrollmentEnrollment, error) {
	rows, err := q.db.Query(ctx, listActiveEnrollmentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnrollmentEnrollment
	for rows.Next() {
		var i EnrollmentEnrollment
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.UserID,
			&i.Status,
			&i.CancelReason,
			&i.EnrolledAt,
			&i.CanceledAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnrollment = `-- name: UpdateEnrollment :execrows
UPDATE enrollment.enrollments
SET status = $3, cancel_reason = $4, enrolled_at = $5, canceled_at = $6, version = version + 1
WHERE id = $1 AND version = $2
`

type UpdateEnrollmentParams struct {
	ID           int64
	Version      int64
	Status       string
	CancelReason string
	EnrolledAt   time.Time
	CanceledAt   *time.Time
}

func (q *Queries) UpdateEnrollment(ctx context.Context, arg UpdateEnrollmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEnrollment,
		arg.ID,
		arg.Version,
		arg.Status,
		arg.CancelReason,
		arg.EnrolledAt,
		arg.CanceledAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
