// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type IdentityRefreshToken struct {
	ID              int64
	UserID          int64
	FamilyID        int64
	TokenHash       []byte
	FamilyExpiresAt time.Time
	ExpiresAt       time.Time
	UsedAt          *time.Time
	RevokedAt       *time.Time
	CreatedAt       time.Time
	UserAgent       string
	IP              string
}

type IdentityUser struct {
	ID          int64
	GoogleSub   string
	Email       string
	Name        string
	AvatarURL   string
	Role        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	LastLoginAt time.Time
}

type PlatformOutboxMessage struct {
	Offset        int64
	Uuid          string
	CreatedAt     pgtype.Timestamp
	Payload       []byte
	Metadata      []byte
	TransactionID pgtype.Uint64
}

type PlatformOutboxOffset struct {
	ConsumerGroup              string
	OffsetAcked                pgtype.Int8
	LastProcessedTransactionID pgtype.Uint64
}
