// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"
)

const getRefreshTokenByHashForUpdate = `-- name: GetRefreshTokenByHashForUpdate :one
SELECT id, user_id, family_id, token_hash, family_expires_at, expires_at, used_at, revoked_at, created_at, user_agent, ip FROM identity.refresh_tokens WHERE token_hash = $1 FOR UPDATE
`

func (q *Queries) GetRefreshTokenByHashForUpdate(ctx context.Context, tokenHash []byte) (IdentityRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHashForUpdate, tokenHash)
	var i IdentityRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.FamilyExpiresAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UserAgent,
		&i.IP,
	)
	return i, err
}

const getUserByGoogleSub = `-- name: GetUserByGoogleSub :one
SELECT id, google_sub, email, name, avatar_url, role, created_at, updated_at, last_login_at FROM identity.users WHERE google_sub = $1
`

func (q *Queries) GetUserByGoogleSub(ctx context.Context, googleSub string) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleSub, googleSub)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.Name,
		&i.AvatarURL,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, google_sub, email, name, avatar_url, role, created_at, updated_at, last_login_at FROM identity.users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.Name,
		&i.AvatarURL,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO identity.refresh_tokens (id, user_id, family_id, token_hash, family_expires_at, expires_at, created_at, user_agent, ip)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertRefreshTokenParams struct {
	ID              int64
	UserID          int64
	FamilyID        int64
	TokenHash       []byte
	FamilyExpiresAt time.Time
	ExpiresAt       time.Time
	CreatedAt       time.Time
	UserAgent       string
	IP              string
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken,
		arg.ID,
		arg.UserID,
		arg.FamilyID,
		arg.TokenHash,
		arg.FamilyExpiresAt,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UserAgent,
		arg.IP,
	)
	return err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO identity.users (id, google_sub, email, name, avatar_url, role, created_at, updated_at, last_login_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertUserParams struct {
	ID          int64
	GoogleSub   string
	Email       string
	Name        string
	AvatarURL   string
	Role        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	LastLoginAt time.Time
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser,
		arg.ID,
		arg.GoogleSub,
		arg.Email,
		arg.Name,
		arg.AvatarURL,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastLoginAt,
	)
	return err
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :exec
UPDATE identity.refresh_tokens SET used_at = $2 WHERE id = $1
`

type MarkRefreshTokenUsedParams struct {
	ID     int64
	UsedAt *time.Time
}

func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, arg MarkRefreshTokenUsedParams) error {
	_, err := q.db.Exec(ctx, markRefreshTokenUsed, arg.ID, arg.UsedAt)
	return err
}

const revokeRefreshFamily = `-- name: RevokeRefreshFamily :exec
UPDATE identity.refresh_tokens SET revoked_at = $2 WHERE family_id = $1 AND revoked_at IS NULL
`

type RevokeRefreshFamilyParams struct {
	FamilyID  int64
	RevokedAt *time.Time
}

func (q *Queries) RevokeRefreshFamily(ctx context.Context, arg RevokeRefreshFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshFamily, arg.FamilyID, arg.RevokedAt)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE identity.users
SET email = $2, name = $3, avatar_url = $4, role = $5, updated_at = $6, last_login_at = $7
WHERE id = $1
`

type UpdateUserParams struct {
	ID          int64
	Email       string
	Name        string
	AvatarURL   string
	Role        string
	UpdatedAt   time.Time
	LastLoginAt time.Time
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.AvatarURL,
		arg.Role,
		arg.UpdatedAt,
		arg.LastLoginAt,
	)
	return err
}
